### ISSUE TITLE
Error in load(out_path) : argument "out_path" is missing, with no default

### ISSUE THREAD

**Issue by beatonan** [rywhale/DanaMartiaMarie#1]
tried to run:
shiny::runGitHub("DanaMartiaMarie", "rywhale")

in RStudio on my machine and the DPC machine and I get the following error:

Error in load(out_path) : argument "out_path" is missing, with no default

When I look at your code, I see that in dana_utils.R "out_path appears to be a required argument for update_thresh:

update_thresh <- function(wsc_ids, out_path) { 
  
  load(out_path)
.....

when it is called in the app.R only 1 argument is supplied:

 update_thresh(unique(gauge_data$STATION_ID))
        
        load("danamartia_cache.rda")
.....
 
If this is the problem, I don't know why it would have worked before but not now, but based on my very limited knowledge of how this code work, this is what I am seeing.

**Comment by rywhale** [comment]
Should be fixed now. Working on my end.
